version: "3"

services:
  db:
    build:
      context: ./db
    ports:
      - "5432:5432"
    restart: always
    networks:
      - election-network

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always
    networks:
      - election-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always
    networks:
      - election-network

networks:
  election-network:
    name: election-network
    driver: bridge
