# Use the official PostgreSQL image from Docker Hub
FROM postgres:16.0-bookworm

# Set environment variables for PostgreSQL
ENV POSTGRES_DB=electiondb \
    POSTGRES_USER=myuser \
    POSTGRES_PASSWORD=mypassword

# Expose the PostgreSQL port
EXPOSE 5432
